In [2]:
medical_charges_url = 'https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv'

In [3]:
from urllib.request import urlretrieve

In [4]:
urlretrieve(medical_charges_url, 'medical.csv')

('medical.csv', <http.client.HTTPMessage at 0x22b26935d10>)

In [5]:
import pandas as pd

In [6]:
medical_df = pd.read_csv('medical.csv')

In [7]:
medical_df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
medical_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [9]:
medical_df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [10]:
%pip install matplotlib seaborn plotly

Requirement already satisfied: matplotlib in d:\machinelearningprojectpractice\.venv\lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in d:\machinelearningprojectpractice\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: plotly in d:\machinelearningprojectpractice\.venv\lib\site-packages (6.8.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: narwhals>=1.15.1 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from plotly) (2.23.0)
Requirement already satisfied: tzdata in d:\machinelearningprojectpractice\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in d:\machinelearningprojectpractice\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import plotly.express as px 
import matplotlib.pyplot as plt 
import seaborn as sns

In [12]:
sns.set_style('whitegrid')
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (10,6)
plt.rcParams['figure.facecolor'] = '#00000000'

In [13]:
fig = px.histogram(medical_df, x = 'age', marginal = 'box',color_discrete_sequence=['red'], nbins = 47, title = 'Distribution of Age')  
fig.update_layout(bargap = 0.1) # add the gap between bars
fig.show()

In [14]:
fig = px.histogram(medical_df,
                   x = 'age', 
                   marginal= 'box', 
                   color= 'sex', 
                   color_discrete_sequence = ["orange", 'green'], 
                   title = 'Annual Medical Charges')
fig.update_layout(bargap= 0.1)
fig.show()

In [15]:
px.histogram(medical_df, x = 'sex', color = 'smoker', title = 'Sex')

In [18]:
fig = px.scatter(medical_df, 
                 x='age', 
                 y='charges', 
                 color='smoker', 
                 opacity=0.8, 
                 hover_data=['sex'], 
                 title='Age vs. Charges')
fig.update_traces(marker_size=5)
fig.show()

In [17]:
fig = px.scatter(medical_df, 
                 x = 'bmi',
                 y='charges',
                 color = 'smoker',
                 opacity = 0.8, 
                 hover_data = ['sex'],
                 title = 'BMI vs. Charges')
fig.update_traces(marker_size = 5)
fig.show()

In [ ]:
# correlation (A positive sign means the values grow together; a negative sign means one decreases as the other increases.) and 0 means no correlation. The closer the value is to 1 or -1, the stronger the correlation.

In [ ]:
medical_df.charges.corr(medical_df.age)

np.float64(0.2990081933306478)

In [20]:
medical_df.charges.corr(medical_df.bmi)

np.float64(0.19834096883362887)

In [ ]:
smoker_charges = {'yes' :1, 'no' : 0}
smoker_numberic = medical_df.smoker.map(smoker_charges)
medical_df.charges.corr(smoker_numberic) # output is 0.78 which close to 1 means that smoker_numberic and charges are positively correlated. This means that as the smoker_numberic increases, the charges also increase. In other words, smokers tend to have higher medical charges than non-smokers.

np.float64(0.7872514304984778)

In [28]:
medical_df['sex_code'] = medical_df.sex.map({'female':0, 'male':1})
medical_df['region_code'] = medical_df.region.map({'southwest':0, 'southeast':1, 'northwest':2, 'northeast':3})
medical_df['smoker_code'] = medical_df.smoker.map({'no':0, 'yes':1})
medical_df.corr(numeric_only = True)

,age,bmi,children,charges,sex_code,region_code,smoker_code
age,1.000000,0.109272,0.042469,0.299008,-0.020856,-0.002127,-0.025019
bmi,0.109272,1.000000,0.012759,0.198341,0.046371,-0.157566,0.003750
children,0.042469,0.012759,1.000000,0.067998,0.017163,-0.016569,0.007673
charges,0.299008,0.198341,0.067998,1.000000,0.057292,0.006208,0.787251
sex_code,-0.020856,0.046371,0.017163,0.057292,1.000000,-0.004588,0.076185
region_code,-0.002127,-0.157566,-0.016569,0.006208,-0.004588,1.000000,0.002181
smoker_code,-0.025019,0.003750,0.007673,0.787251,0.076185,0.002181,1.000000

In [29]:
sns.heatmap(medical_df.corr(numeric_only = True), annot = True, cmap = 'red')
plt.title('Correlation Matrix');

KeyError: "'red' is not a valid value for colormap. Did you mean one of: 'Paired', 'grey', 'Reds'?"