In [ ]:
%pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.3
cycler                  0.12.1
debugpy                 1.8.20
decorator               5.2.1
executing               2.2.1
fonttools               4.62.1
ipykernel               7.2.0
ipython                 9.11.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
joblib                  1.5.3
jupyter_client          8.8.0
jupyter_core            5.9.1
kiwisolver              1.5.0
matplotlib              3.10.8
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.3
packaging               26.0
pandas                  3.0.1
parso                   0.8.6
pillow                  12.1.1
pip                     26.0.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                2.19.2
pyparsing               3.3.2
python-dateutil         2.9.0.post0
pyzmq                   27.1.0
scikit-learn            1.8.0
scipy                   1.17.1
six                     1.17.0
stack-data              0.6.3
threadpoolctl           3.6.0
tornado                 6.5.5
traitlets               5.14.3
tzdata                  2025.3
wcwidth                 0.6.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

# Series — 1D labeled array
s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'])
s['b']      # 20
s[s > 15]  # filter: b=20, c=30, d=40

b    20
c    30
d    40
dtype: int64

In [ ]:
//hello

In [27]:
df = pd.DataFrame({
  'age':    [25, 28,32,37, 45,60],
    'salary': [50000, 75000, 60000, 90000,10000,15000],
    'dept':   ['Eng', 'HR', 'Eng', 'Finance','HR','Finance']
})

In [28]:
arr = np.random.randn(4, 3)
df2 = pd.DataFrame(arr, columns=['A', 'B', 'C'])

df.describe()

             age        salary
count   6.000000      6.000000
mean   37.833333  50000.000000
std    12.952477  32093.613072
min    25.000000  10000.000000
25%    29.000000  23750.000000
50%    34.500000  55000.000000
75%    43.000000  71250.000000
max    60.000000  90000.000000

In [ ]:
df = pd.DataFrame({
    'name': ['Alice','Bob','Carol','Dave'],
    'age':  [25, 32, 28, 45],
    'score':[88, 72, 95, 61]
})

# Select columns
df['age']             # Series
df[['name','score']]  # DataFrame
df.loc[0]  
df.loc[1:3, ['age','score','name']]
df[df['score']>0] 
df.iloc[:2, 1:]

   age  score   name
1   32     72    Bob
2   28     95  Carol
3   45     61   Dave